[env:m5stack-cardputer]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.f_flash = 80000000L
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_ldf_mode = deep
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  m5stack/M5Cardputer@^1.1.1
  bblanchon/ArduinoJson@^7.0.0
